CREATE TABLE Book (
    BookID CHAR(10) NOT NULL,
    LessorID CHAR(10) NOT NULL,
    Tagline VARCHAR(500),
    Status BOOLEAN DEFAULT 0 NOT NULL,
    B_name VARCHAR(100) NOT NULL,
    ISBN INT(13),
    Full_price DECIMAL(10, 2),
    P_time INT(2),
    P_year INT(4),
    Publisher VARCHAR(100),
    Datebook DATE NOT NULL,
    Rent_Price_Per_Day INT(4) NOT NULL,
    Security_Deposit INT(5) NOT NULL,
    Cost INT(5),
    Status_lo VARCHAR(50),
    Logic_com VARCHAR(100),
    Start_date DATE,
    End_date DATE,
    TenantID VARCHAR(10),
    CID VARCHAR(2) NOT NULL,
    total_rental INT DEFAULT 0,
    PRIMARY KEY (BookID, LessorID),
    FOREIGN KEY (LessorID) REFERENCES Member(MemberID),
    FOREIGN KEY (TenantID) REFERENCES Member(MemberID),
    FOREIGN KEY (CID) REFERENCES Category(CID)
);
